//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalTaskFlights.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinalTaskFlights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Title&quot;,
        ///            &quot;size&quot;: &quot;Large&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;&lt;Header&gt;&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Subtitle&quot;,
        ///            &quot;text&quot;: &quot;One Way Flight&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;FactSet&quot;,
        ///            &quot;facts&quot;: [
        ///                {
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlightDetailsOneWay {
            get {
                return ResourceManager.GetString("FlightDetailsOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Title&quot;,
        ///            &quot;size&quot;: &quot;Large&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;&lt;Header&gt;&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Subtitle&quot;,
        ///            &quot;text&quot;: &quot;One Way Flight&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;FactSet&quot;,
        ///            &quot;facts&quot;: [
        ///                {
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlightDetailsOneWayRental {
            get {
                return ResourceManager.GetString("FlightDetailsOneWayRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Title&quot;,
        ///            &quot;size&quot;: &quot;Large&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;&lt;Header&gt;&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Subtitle&quot;,
        ///            &quot;text&quot;: &quot;Two ways flight&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;FactSet&quot;,
        ///            &quot;facts&quot;: [
        ///                {
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlightDetailsTwoWays {
            get {
                return ResourceManager.GetString("FlightDetailsTwoWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Title&quot;,
        ///            &quot;size&quot;: &quot;Large&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;&lt;Header&gt;&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Subtitle&quot;,
        ///            &quot;text&quot;: &quot;Two ways flight&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;FactSet&quot;,
        ///            &quot;facts&quot;: [
        ///                {
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlightDetailsTwoWaysRental {
            get {
                return ResourceManager.GetString("FlightDetailsTwoWaysRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;type&quot;: &quot;AdaptiveCard&quot;,
        ///    &quot;body&quot;: [
        ///        {
        ///            &quot;type&quot;: &quot;TextBlock&quot;,
        ///            &quot;id&quot;: &quot;Title&quot;,
        ///            &quot;size&quot;: &quot;Large&quot;,
        ///            &quot;weight&quot;: &quot;Bolder&quot;,
        ///            &quot;text&quot;: &quot;&lt;Header&gt;&quot;,
        ///            &quot;wrap&quot;: true
        ///        },
        ///        {
        ///            &quot;type&quot;: &quot;FactSet&quot;,
        ///            &quot;facts&quot;: [
        /// 	{
        ///                    &quot;title&quot;: &quot;Rental Length:&quot;,
        ///                    &quot;value&quot;: &quot;&lt;RentalLenght&gt;&quot;
        ///                },
        ///                {
        ///                    &quot;title&quot;: &quot;Passengers Number:&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RentalDetails {
            get {
                return ResourceManager.GetString("RentalDetails", resourceCulture);
            }
        }
    }
}
